apiVersion: v1
kind: Service
metadata:
  name: {{ include "face-verification.fullname" . }}
  labels:
    {{- include "face-verification.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "face-verification.selectorLabels" . | nindent 4 }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "face-verification.fullname" . }}-metrics
  labels:
    {{- include "face-verification.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "face-verification.selectorLabels" . | nindent 4 }}
{{- end }}
